
from shutil import move
import time
import sys

def BeholdAnimate(): #ANIMATE PROJECT BEHOLDER TITLE
    print("W", end='\r')
    time.sleep(0.1)
    print("We", end='\r')
    time.sleep(0.1)
    print("Wel", end='\r')
    time.sleep(0.1)
    print("Welc", end='\r')
    time.sleep(0.1)
    print("Welco", end='\r')
    time.sleep(0.1)
    print("Welcome", end='\r')
    time.sleep(0.1)
    print("Welcome T", end='\r')
    time.sleep(0.1)
    print("Welcome To", end='\r')
    time.sleep(0.1)
    print("Welcome To P", end='\r')
    time.sleep(0.1)
    print("Welcome To Pr", end='\r')
    time.sleep(0.1)
    print("Welcome To Pro", end='\r')
    time.sleep(0.1)
    print("Welcome To Proj", end='\r')
    time.sleep(0.1)
    print("Welcome To Proje", end='\r')
    time.sleep(0.1)
    print("Welcome To Projec", end='\r')
    time.sleep(0.1)
    print("Welcome To Project", end='\r')
    time.sleep(0.1)
    print("Welcome To Project B", end='\r')
    time.sleep(0.05)
    print("Welcome To Project Be", end='\r')
    time.sleep(0.1)
    print("Welcome To Project Beh", end='\r')
    time.sleep(0.1)
    print("Welcome To Project Beho", end='\r')
    time.sleep(0.1)
    print("Welcome To Project Behol", end='\r')
    time.sleep(0.1)
    print("Welcome To Project Behold", end='\r')
    time.sleep(0.1)
    print("Welcome To Project Beholde", end='\r')
    time.sleep(0.1)
    print("Welcome To Project Beholder", end='\r')
    time.sleep(0.1)
    print("Welcome To Project Beholder.", end='\r')
    time.sleep(0.5)
    print("                                               Welcome To Project Beholder.", end='\r')
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("                                               ⚔Enter your name to begin.⚔")


def ClearWindow_(): #CLEAR THE WHOLE WINDOW
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")

def MoveUpTop_(): #MOVE TEXT TO TOP
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")

ClearWindow_()

print("Loading", end='\r') #Print loading, do a carriage return
time.sleep(0.3) #Pause for 0.3 seconds
print("Loading.", end='\r')
time.sleep(0.3)
print("Loading..", end='\r')
time.sleep(0.3)
print("Loading...")
MoveUpTop_()

ClearWindow_
BeholdAnimate()

name = input("                                               ")

